# Example Site settings

name: jekyllx

google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: '(c) 2022 <a href="#">jekyllx</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
